name: freecol-linux # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: FreeCol is a 4X video game, a clone of Sid Meier's Colonization.
description: |
  While remaining faithful to the original in terms of mechanics and gameplay, FreeCol features redesigned graphics. Moreover, in addition to the classical Colonization rules, it features an additional ruleset that incorporates ideas that didn't make it to the final version of Meier's game, requests by fans and original concepts like new European players with new national bonuses.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  freecol_icon.png
title: FreeCol

apps:
  freecol:
    command: startfreecol
parts:
  freecol:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      freecol: build/
      freecol.1: man/man1/

architectures:
  - build-on: amd64

